<?php

return [
    'Gulshan-e-Iqbal',
    'Gulistan-e-Johar',
    'North Nazimabad',
    'Nazimabad',
    'Federal B Area',
    'Malir',
    'Korangi',
    'Landhi',
    'Shah Faisal Colony',
    'Saddar',
    'Clifton',
    'Defence (DHA)',
    'PECHS',
    'Gulshan-e-Maymar',
    'North Karachi',
    'Orangi Town',
    'Baldia Town',
    'SITE Area',
    'Lyari',
    'Kemari',
    'Sharea Faisal',
    'Bahadurabad',
    'Tariq Road',
    'Garden',
    'Liaquatabad',
    'Nagan Chowrangi',
    'Surjani Town',
    'Scheme 33',
    'University Road',
    'Model Colony',
    'Airport Area',
];